apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecsdemo-frontend
  namespace: apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
  - namespace: apps
    server: https://kubernetes.default.svc
  sourceRepos:
  - '{{ .Values.spec.apps.ecsdemo-frontend.repoURL }}'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecsdemo-frontend
  namespace: apps
  labels: |
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: ecsdemo-frontend
  destination:
    namespace: apps
    server: '{{ .Values.spec.destination.server }}'
  source:
    repoURL: '{{ .Values.spec.apps.ecsdemo-frontend.repoURL }}'
    targetRevision: '{{ .Values.spec.apps.ecsdemo-frontend.targetRevision }}'
    path: '{{ .Values.spec.apps.ecsdemo-frontend.path }}'
    helm:
      values: |
        {{ toYaml .Values.spec.apps.ecsdemo-frontend.path | nindent 8 }}   #! CHANGED
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=false

